# Generated by Django 5.2.8 on 2025-11-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emirate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailLiftBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToteCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('chassis_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('truck_reg_date', models.DateField()),
                ('insurance_document', models.FileField(upload_to='documents/')),
                ('insurance_expiry_date', models.DateField()),
                ('mulkia_registration_date', models.DateField()),
                ('mulkia_document', models.FileField(upload_to='documents/')),
                ('permit_registration_date', models.DateField()),
                ('permit_document', models.FileField(upload_to='documents/')),
                ('tl_no', models.IntegerField()),
                ('tc_no', models.IntegerField()),
                ('tc_owner', models.CharField(max_length=100)),
                ('salik_account_no', models.CharField(max_length=100)),
                ('salik_tag_no', models.CharField(max_length=100)),
                ('darb_ac_no', models.CharField(max_length=100)),
                ('lift_gate', models.BooleanField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('truck_photos', models.ImageField(upload_to='images/')),
                ('branding_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.brandingstatus')),
                ('emirates_permit', models.ManyToManyField(to='office_user.emirate')),
                ('gps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.gps')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.make')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.status')),
                ('tail_lift_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.tailliftbrand')),
                ('tote_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.totecapacity')),
                ('vehicle_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.vehiclecapacity')),
                ('vehicle_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.vehicleconcept')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_user.vehicletype')),
            ],
        ),
    ]
