# Generated by Django 5.2.8 on 2025-11-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandingstatus',
            options={'verbose_name': 'Branding status', 'verbose_name_plural': 'Branding statuss'},
        ),
        migrations.AlterModelOptions(
            name='emirate',
            options={'verbose_name': 'Emirate', 'verbose_name_plural': 'Emirates'},
        ),
        migrations.AlterModelOptions(
            name='gps',
            options={'verbose_name': 'GPS', 'verbose_name_plural': 'GPSs'},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'verbose_name': 'Make', 'verbose_name_plural': 'Makes'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuss'},
        ),
        migrations.AlterModelOptions(
            name='tailliftbrand',
            options={'verbose_name': 'Tail lift brand', 'verbose_name_plural': 'Tail lift brands'},
        ),
        migrations.AlterModelOptions(
            name='totecapacity',
            options={'verbose_name': 'Tote capacity', 'verbose_name_plural': 'Tote capacitys'},
        ),
        migrations.AlterModelOptions(
            name='vehiclecapacity',
            options={'verbose_name': 'Vehicle capacity', 'verbose_name_plural': 'Vehicle capacitys'},
        ),
        migrations.AlterModelOptions(
            name='vehicleconcept',
            options={'verbose_name': 'Vehicle concept', 'verbose_name_plural': 'Vehicle concepts'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemaster',
            options={'verbose_name': 'Vehicle master', 'verbose_name_plural': 'Vehicle masters'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Vehicle type', 'verbose_name_plural': 'Vehicle types'},
        ),
    ]
