# Generated by Django 5.2.8 on 2025-11-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_user', '0003_seed_dropdowns'),
        ('office_user', '0003_seed_vehicle_dropdowns'),
    ]

    operations = [
    ]
