# Generated by Django 5.2.8 on 2025-11-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_user', '0004_merge_0003_seed_dropdowns_0003_seed_vehicle_dropdowns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Change log',
                'verbose_name_plural': 'Change logs',
                'db_table': 'change_log',
            },
        ),
    ]
