# Generated by Django 5.2.8 on 2025-11-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_user', '0005_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
