# Generated by Django 5.2.8 on 2025-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_user', '0006_changelog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='changelog',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
