# Generated by Django 5.2.8 on 2025-11-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_user', '0007_changelog_chassis_number_changelog_plate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemaster',
            old_name='insurance_expiry_date',
            new_name='insurance_registration_date',
        ),
    ]
