# Generated by Django 5.2.8 on 2025-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_user', '0008_rename_insurance_expiry_date_vehiclemaster_insurance_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaster',
            name='insurance_registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='mulkia_registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='permit_registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='truck_registration_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
